version: "3.8"
services:
  client:
    build:
      context: ./client
    container_name: go-grpc-client
    network_mode: host
    stdin_open: true
    tty: true
  server:
    build:
      context: ./server
    container_name: go-grpc-server
    ports:
      - "50051:50051"
    environment:
      - AOAI_KEY=your-azureopenai-key
      - AOAI_ENDPOINT=your-azureopenai-endpoint
      - AOAI_VERSION=your-azureopenai-rest-version
      - AOAI_DEPLOYNAME=your-azureopenai-deploy-name
networks:
  go-net:
    driver: bridge
